### ISSUE TITLE
Adopt a versioning scheme

### ISSUE THREAD

**Issue by DeeDeeG** [atom-ide-community/apm#8]
We need some kind of version scheme that npm will work with.

I'd like us to either:
- bump the core version bits (`x.y.z`)
- use hyphens and/or dots (`2.5.0-some.stuff-here.0`).
  - Example: `2.5.0-node-12-4-0.0`,  next patch release is `2.5.0-node-12-4-0.1`
  - Example: `2.5.0-community.0.1.0`, next patch release is `2.5.0-community.0.1.1`
  - We can mix and match hyphens and dots, pretty much whatever way we want.
  - Node will treat these as "prerelease" versions.

The things I suggested above are semver compliant.

Docs: https://docs.npmjs.com/misc/semver#versions -- https://semver.org/

**Comment by DeeDeeG** [comment]
> The things I suggested above are semver compliant.

And so is `2.5.0+0.1.0`, but `npm` seems to chop off plus signs `+` and anything to the right, so we can't do that.

**Comment by DeeDeeG** [comment]
cc @aminya please take a look and let me know what you think when you get the time. The release we published ended up with version `2.5.0`, which seems unintended given the `2.5.0+0.1.0` tag here, and the version `2.5.0+0.1.0` in our `package.json`.

Looks like we need to stick to hyphens and dots, no pluses.

**Comment by aminya** [comment]
I took `2.5.0-atomic.1`

**Comment by DeeDeeG** [comment]
That'll work.

I think it's not super obvious in a "working with upstream" context whose that is, but it'll at least publish with that version.

**Comment by aminya** [comment]
Yes. That works for us. The only consumer of our `apm` is our Atom. So this is not important. 

Closing this.

**Comment by DeeDeeG** [comment]
Some day I picture Atom might want our version rather than bumping theirs. Theirs is, um... I don't want to say abandonware, it's early to say that, but it almost looks like it's not maintained, period.

---

I think they're only updating it when Atom development absolutely demands it.

The proper Visual Studio support greater than version 2015 is a really great quality of life improvement, and I can't really picture why they haven't merged it other than they don't have the time, or they're afraid to touch it, lest it breaks.

Afraid to touch it would be very near to abandonware, except that they need it, so they will go in and fix things when absolutey needed I guess. Not a great level of maintenance that is. I'd like it to be reasonably, proactively current. And nice to use. And so on.

Okay so none of that means usptream will use our versions. And if they have thoughts and opinions about our versioning scheme, they can certainly let us know. I'm all ears, upstream, if you're reading this! Would love to work with you on this piece of the Atom ecosystem! :heart:

**Comment by DeeDeeG** [comment]
Upstream merged the Node v12.0.0 bump.

But we already have that change here. And updating the core version `2.5.0` --> `2.5.1` would mess with our version scheme: `[core]-atomic.[atomic_version]`

Let's not merge upstream to here until they add a change (a feature, a bugfix, etc.) that's not on this fork yet.

There's no reason to shake up our versioning scheme just to "integrate a change we already have" (Node 12.0.0).

Since our changes are so few, I will _consider_ rebasing on top of upstream for this repo, but the default posture is still to just merge upstream, keeping the full preserved history. and using (non-destructive) merge commits.
